entryPoints:
  wan:
    http:
      encodedCharacters:
        allowEncodedSlash: false          # %2F - Default: true
        allowEncodedBackSlash: false      # %5C - Default: true
        allowEncodedNullCharacter: false  # %00 - Default: true
        allowEncodedSemicolon: false      # %3B - Default: true
        allowEncodedPercent: false        # %25 - Default: true
        allowEncodedQuestionMark: false   # %3F - Default: true
        allowEncodedHash: false           # %23 - Default: true
http:
  middlewares:
    block-path-middleware:
      plugin:
        block-path-plugin:
          regex: [ "^/api(.*)", "^/settings(.*)", "^/users(.*)", ]
          code: 404
    method-whitelist-plugin:
      plugin:
        method-whitelist:
          Message: "Method Not Allowed"
          Methods: [ GET, OPTIONS, ]
    secure-headers:
      headers:
        accessControlAllowHeaders: [ "*", ]
        accessControlAllowMethods: [ GET, OPTIONS, ]
        accessControlAllowOriginList: [ https://www.bob.house, https://miasma.bob.house, ]
        accessControlMaxAge: 100
        addVaryHeader: true
        browserXssFilter: true
        contentSecurityPolicy: >-
          default-src 'self';
          script-src 'self';
          connect-src 'self';
          img-src 'self';
          style-src 'self' 'unsafe-inline';
          object-src 'none';
          base-uri 'none';
          frame-ancestors 'none';
        contentTypeNosniff: true
        customFrameOptionsValue: "SAMEORIGIN"
        customResponseHeaders:
          Cross-Origin-Embedder-Policy: require-corp
          Cross-Origin-Opener-Policy: same-origin
          Cross-Origin-Resource-Policy: same-origin
          server: ""
          x-powered-by: ""
        frameDeny: true
        referrerPolicy: same-origin
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
  routers:
    homeassistant-router:
      entryPoints:
        - "lan"
      rule: "Host(`homeassistant.bob.house`)"
      service: "homeassistant-service"
      tls: "true"
    iot-switch-router:
      entryPoints:
        - "lan"
      rule: "Host(`iot-switch.bob.house`)"
      service: "iot-switch-service"
      tls: "true"
    main-router-router:
      entryPoints:
        - "lan"
      rule: "Host(`main-router.bob.house`)"
      service: "main-router-service"
      tls: "true"
    main-switch-router:
      entryPoints:
        - "lan"
      rule: "Host(`main-switch.bob.house`)"
      service: "main-switch-service"
      tls: "true"
  services:
    homeassistant-service:
      loadBalancer:
        servers:
        - url: "http://192.168.20.80:8123"
    iot-switch-service:
      loadBalancer:
        servers:
        - url: "http://192.168.20.5"
    main-router-service:
      loadBalancer:
        servers:
        - url: "http://192.168.1.1"
    main-switch-service:
      loadBalancer:
        servers:
        - url: "http://192.168.1.5"
