endpoints:
  - name: docker-wan1 .20
    group: dns .20
    url: 192.168.20.60
    dns:
      query-name: docker-wan1.bob.house
      query-type: CNAME
    conditions: &conditions-definition
      - "[BODY] == wan1.bob.house."
      - "[DNS_RCODE] == NOERROR"
    alerts: &alerts-definition
      - type: ntfy

  - name: glances-kayshon .20
    group: dns .20
    url: 192.168.20.60
    dns:
      query-name: glances-wan1.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: kopia-wan1 .20
    group: dns .20
    url: 192.168.20.60
    dns:
      query-name: kopia-wan1.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: leafwiki .20
    group: dns .20
    url: 192.168.20.60
    dns:
      query-name: www.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: miasma .20
    group: dns .20
    url: 192.168.20.60
    dns:
      query-name: miasma.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: traefik-wan1 .20
    group: dns .20
    url: 192.168.20.60
    dns:
      query-name: traefik-wan1.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: webhooks .20
    group: dns .20
    url: 192.168.20.60
    dns:
      query-name: webhooks.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition
