endpoints:
  - name: docker-wan1 .1
    group: dns .1
    url: 192.168.1.50
    dns:
      query-name: docker-wan1.bob.house
      query-type: CNAME
    conditions: &conditions-definition
      - "[BODY] == wan1.bob.house."
      - "[DNS_RCODE] == NOERROR"
    alerts: &alerts-definition
      - type: ntfy

  - name: glances-kayshon .1
    group: dns .1
    url: 192.168.1.50
    dns:
      query-name: glances-wan1.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: kopia-wan1 .1
    group: dns .1
    url: 192.168.1.50
    dns:
      query-name: kopia-wan1.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: leafwiki .1
    group: dns .1
    url: 192.168.1.50
    dns:
      query-name: www.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: miasma .1
    group: dns .1
    url: 192.168.1.50
    dns:
      query-name: miasma.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: traefik-wan1 .1
    group: dns .1
    url: 192.168.1.50
    dns:
      query-name: traefik-wan1.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition

  - name: webhooks .1
    group: dns .1
    url: 192.168.1.50
    dns:
      query-name: webhooks.bob.house
      query-type: CNAME
    conditions: *conditions-definition
    alerts: *alerts-definition
