schedule: CRON_TZ=Etc/UTC 15,45 * * * *
retry_policy:
  limit: 0
steps:
  - id: get_origin_with_proxy
    action: ssh.run
    with:
      user: root
      host: freeman.bob.house
      key: /run/secrets/id_rsa
      known_host_file: /run/secrets/known_hosts
      command: |
        curl \
          --header 'Accept: application/json; charset=utf-8' \
          --header 'User-Agent: Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405' \
          --proxy 'http://squid.bob.house:3128' \
          --silent \
          --url 'https://httpbin.dev/anything' \
          --verbose
    output:
      ip:
        from: stdout
        decode: json
        select: .origin
  - id: get_origin_without_proxy
    action: ssh.run
    with:
      user: root
      host: freeman.bob.house
      key: /run/secrets/id_rsa
      known_host_file: /run/secrets/known_hosts
      command: |
        curl \
          --header 'Accept: application/json; charset=utf-8' \
          --header 'User-Agent: Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405' \
          --silent \
          --url 'https://httpbin.dev/anything' \
          --verbose
    output:
      ip:
        from: stdout
        decode: json
        select: .origin
  - id: test
    run: |
      if [ "${get_origin_with_proxy.output.ip}" != "${get_origin_without_proxy.output.ip}" ]
      then
        printf "true"
      else
        printf "false"
      fi
    depends: [ get_origin_with_proxy, get_origin_without_proxy, ]
    preconditions:
      - condition: "${get_origin_with_proxy.output.ip}"
        expected: "re:.+"
      - condition: "${get_origin_without_proxy.output.ip}"
        expected: "re:.+"
    output:
      success:
        from: stdout
        decode: text
  - id: notify
    action: http.request
    with:
      method: POST
      url: https://ntfy.bob.house/364d0bdedc5b0bc275b048dc42e342460fb535dc1efcc5daf35460bf4ba4c26e
      headers:
        Accept: application/json
        Content-Type: text/plain
        Priority: high
        Tags: office,computer
        Title: "proxy failed"
        User-Agent: Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405
      silent: false
      timeout: 5
      debug: true
    depends: test
    preconditions:
      - condition: "${test.output.success}"
        expected: "false"
